### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by epeleh** [Max-Sir/My_JavaScript_Projects#1]
https://github.com/Max-Sir/My_JavaScript_Projects/blob/e5475bb4e5857680dde8dc1e8ba3f7dfeec14d88/Task%20List/app.js#L17
The task removal logic doesn't work at all. Should be: `taskList.addEventListener('click', removeTask);`

---

https://github.com/Max-Sir/My_JavaScript_Projects/blob/e5475bb4e5857680dde8dc1e8ba3f7dfeec14d88/Task%20List/app.js#L29-L31
There should be a `return` statement after the `alert`

---

https://github.com/Max-Sir/My_JavaScript_Projects/blob/e5475bb4e5857680dde8dc1e8ba3f7dfeec14d88/Task%20List/app.js#L58
Because of the [conditional branching](https://github.com/Max-Sir/My_JavaScript_Projects/blob/main/Task%20List/app.js#L29) above, this line might be skipped. So let's move it to the top of [the function](https://github.com/Max-Sir/My_JavaScript_Projects/blob/main/Task%20List/app.js#L27)

---

https://github.com/Max-Sir/My_JavaScript_Projects/blob/e5475bb4e5857680dde8dc1e8ba3f7dfeec14d88/Task%20List/index.html?plain=1#L35-L39
The `clear-tasks` button deletes itself when you click on it. So it should be changed to:
```html
    <a href="#" class="clear-tasks btn black" id="clearme">
        Clear Tasks
    </a>
    <ul class="collection">
    </ul>
```

---

https://github.com/Max-Sir/My_JavaScript_Projects/blob/e5475bb4e5857680dde8dc1e8ba3f7dfeec14d88/Book%20List/app_es6.js?plain=1#L56
```
app_es6.js:56 Uncaught ReferenceError: e is not defined
    at UI.showAlert (app_es6.js:56:9)
    at HTMLFormElement.<anonymous> (app_es6.js:94:12)
showAlert @ app_es6.js:56
(anonymous) @zapp_es6.js:94
```

---

https://github.com/Max-Sir/My_JavaScript_Projects/blob/e5475bb4e5857680dde8dc1e8ba3f7dfeec14d88/Book%20List/app_es6.js?plain=1#L95
The page reloads and all books are cleared after the submit button is pressed: the logic of the app is broken. `preventDefault` should be placed at the top of [the function](https://github.com/Max-Sir/My_JavaScript_Projects/blob/e5475bb4e5857680dde8dc1e8ba3f7dfeec14d88/Book%20List/app_es6.js?plain=1#L69)

**Comment by Laraib-Azmat** [comment]
Can You assign me this? i can resolve your issues
